- name: Upgrade | Download upgrade_win.ps1
  win_get_url:
    url: "{{ dcos['config']['bootstrap_url'] }}/{{ dcos_version_specifier }}/genconf/serve/windows/upgrade_from_{{ dcos['version_to_upgrade_from'] }}/latest/dcos_node_upgrade.ps1"
    dest: "{{ base_windows_dir }}\\upgrade_win.ps1"
    force: yes

- name: Windows Upgrade | DC/OS Upgrade
  block:
    - name: Windows Upgrade | Run DC/OS agent upgrade
      win_shell: "{{ base_windows_dir }}\\upgrade_win.ps1"
      register: install_shell_stdout

  always:
    - name: Windows Installation | Output log into ansible_playbook.log
      win_copy:
        content: |
          ================================================
          Ansible STDOUT:
          ------------------------------------------------
          {{ install_shell_stdout.stdout }}
          ================================================
          Ansible STDERR:
          ------------------------------------------------
          {{ install_shell_stdout.stderr }}
          ================================================
        dest: "{{ base_windows_dir }}\\var\\log\\ansible_playbook.log"
